apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - manifests/namespace.yaml
# Mongo
  - manifests/mongodb/persistentVolume.yaml
  - manifests/mongodb/persistentVolumeClaim.yaml
  - manifests/mongodb/secrets.yaml
  - manifests/mongodb/service.yaml
  - manifests/mongodb/deployment.yaml