apiVersion: apps/v1
kind: Deployment
metadata:
  name: remainders-backend
  namespace: remainders
spec:
  replicas: 1
  selector:
    matchLabels:
      app: remainders-backend
  template:
    metadata:
      labels:
        app: remainders-backend
    spec:
      containers:
        - name: remainders-backend
          image: IMAGE
          env:
            - name: APP_PORT
              value: "8888"
            - name: APP_DB
              valueFrom:
                secretKeyRef:
                  name: backend
                  key: APP_DB
            - name: APP_DB_USER
              valueFrom:
                secretKeyRef:
                  name: backend
                  key: APP_DB_USER
            - name: APP_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: backend
                  key: APP_DB_PASSWORD
            - name: APP_DB_URI
              valueFrom:
                secretKeyRef:
                  name: backend
                  key: APP_DB_URI
            - name: ALLOWED_ORIGINS
              value: "*"
          resources:
            limits:
              cpu: "15m"
              memory: "30Mi"
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8888
            initialDelaySeconds: 30
            periodSeconds: 10
