GET https://localhost:8888/api/v1/latest HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiTWF0dGkgTcO2dHTDtm5lbiIsImV4cCI6MTY0MjMyNDUyMX0.SQRF0Opfd-Y5dPUOjFSEw06aCBpo_YkQ4OSkBsvA9X8