GET https://localhost:8888/api/v1/search/matti HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik1hdHRpIE3DtnR0w7ZuZW4ifQ.2U4_F9eLf3SzatIY30Puk5kN6dFVnr1LhmiryP6O7M8